[features]
seeds = false
skip-lint = false

[programs.mainnet]
digitalpulse_tld = "AoK7A4kRVL6UYA4ydwUkjEXujBBPjcVh5VZvM4i8uKVt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "/home/ubuntu/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
